version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass your-password
    ports:
      - "6379:6379"
    networks:
      - back-office
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: your-root-password
    ports:
      - "3307:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - back-office
  # order_service:
  #   image: order_service
  #   build:
  #     dockerfile: ./order/Dockerfile
  #   depends_on:
  #     - database
  #     - redis
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - back-office

networks:
  back-office:
