version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass your-password
    ports:
      - "6379:6379"
    networks:
      - back-office
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: your-root-password
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - back-office
  order_service:
    image: order_service
    build:
      dockerfile: ./order/Dockerfile
    environment:
      - DATABASE_URL=mariadb://orders-username:orders-password@database:3306/orders
      - CELERY_BROKER=redis://:your-password@redis:6379/0
    depends_on:
      - database
      - redis
    ports:
      - "80:80"
    networks:
      - back-office
  payment_service:
    image: payment_service
    build:
      dockerfile: ./payment/Dockerfile
    environment:
      - DATABASE_URL=mariadb://payment-username:payment-password@database:3306/payment
      - CELERY_BROKER=redis://:your-password@redis:6379/0
    depends_on:
      - database
      - redis
    networks:
      - back-office
  inventory_service:
    image: inventory_service
    build:
      dockerfile: ./inventory/Dockerfile
    environment:
      - DATABASE_URL=mariadb://inventory-username:inventory-password@database:3306/inventory
      - CELERY_BROKER=redis://:your-password@redis:6379/0
    depends_on:
      - database
      - redis
    networks:
      - back-office
  delivery_service:
    image: delivery_service
    build:
      dockerfile: ./delivery/Dockerfile
    environment:
      - DATABASE_URL=mariadb://delivery-username:delivery-password@database:3306/delivery
      - CELERY_BROKER=redis://:your-password@redis:6379/0
    depends_on:
      - database
      - redis
    networks:
      - back-office

networks:
  back-office:
