global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "order_service"
    static_configs:
      - targets: ["order_service:80"]

  - job_name: "payment_service"
    static_configs:
      - targets: ["payment_service"]

  - job_name: "inventory_service"
    static_configs:
      - targets: ["inventory_service"]

  - job_name: "delivery_service"
    static_configs:
      - targets: ["delivery_service"]