global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:16686"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  
  - job_name: "order_service"
    static_configs:
      - targets: ["order_service:80"]

  - job_name: "payment_service"
    static_configs:
      - targets: ["payment_service:70"]

  - job_name: "inventory_service"
    static_configs:
      - targets: ["inventory_service:60"]

  - job_name: "delivery_service"
    static_configs:
      - targets: ["delivery_service:50"]